version: '3.9'
services:
  app:
    container_name: "django-chat-app"
    image: "istiaq/django-chat-app"
    # env_file:
    #   - .env
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - ./src:/src
    ports:
      - 5000:8000